### PR TITLE
Add support for app export syntax

### PR DESCRIPTION
**Pull request by dricholm**
Issue #1 

Date syntax will now be accepted both ways:
* YYYY.MM.DD dayName
* YYYY/MM/DD(dayName)

Also time, user and message separated by tabs is supported now.

I was not sure whether to change the version inside `package.json`. Is it needed for updating the package on npm later?

### CODE REVIEW

**Comment by meyfa** [comment]
First off: Thanks a lot for contributing!

This looks good, except for one small bug in the date matching RegEx (line 37). At the end, there is `\(.\)` — which is totally valid for the Japanese example you provided and also for the test case (my mistake, sorry!). But with the English locale and possibly with others as well, there are more characters than one (e.g. "2018/04/16(Mon)"). Could you change that part so that it reads `\(.+\)`?

> I was not sure whether to change the version inside package.json. Is it needed for updating the package on npm later?

Thanks for asking! No, you do not need to worry. Right before updating the NPM package, a final commit is created that changes the version field.

**Comment by dricholm** [comment]
I see, I didn't think about that. I will fix it.

Do you think `\(.+\)` or `\(\w+\)` would be better?

I could also add a new test case for an english example as you said: "2018/04/16(Mon)"

**Comment by meyfa** [comment]
> Do you think `\(.+\)` or `\(\w+\)` would be better?

Because `\w` is defined as equivalent to `[A-Za-z0-9_]` (see for example https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), it would not match Japanese characters, so I think it should be `\(.+\)`.

> I could also add a new test case for an english example as you said: "2018/04/16(Mon)"

That would be nice, thanks!

**Comment by dricholm** [comment]
Yes, you are right. `\w` would not detect special characters.

I pushed a new commit which also includes a new test case.

**Comment by meyfa** [comment]
Seems perfect! Merging.

**Pull request merged**
